export const config = {
  FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDERID: import.meta.env.VITE_FIREBASE_MESSAGING_SENDERID,
  FIREBASE_APPID: import.meta.env.VITE_FIREBASE_APPID,
  FIREBASE_MEASUREMENTID: import.meta.env.VITE_FIREBASE_MEASUREMENTID,
};
